"""Modelo ReporteBimestral y ajustes

Revision ID: c5c6d046cf9d
Revises: cdd1a3477383_alinear_proyecto_con_formulario
Create Date: 2025-08-21 13:29:18.981314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c6d046cf9d'
down_revision = 'cdd1a3477383_alinear_proyecto_con_formulario'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos_proyectos', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_proyecto', ['user_id', 'proyecto_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos_proyectos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_proyecto', type_='unique')

    # ### end Alembic commands ###
